[tool.poetry]
name = "bookstore"
version = "0.1.0"
<<<<<<< HEAD
description = "Bookstore API"
authors = ["Leonardo <leonardoitaloapbr@gmail.com>"]
=======
description = "bookstore API"
authors = ["CJosueAK47 <83555240+CJosueAK47@users.noreply.github.com>"]
>>>>>>> f6ac5dfbe4ee90a476827f702ef4cb128c0e3ee7
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^7.4.3"
factory-boy = "^3.3.0"
<<<<<<< HEAD
django = "^4.2.7"
djangorestframework = "^3.14.0"
django-extensions = "^3.2.3"
django-debug-toolbar = "^4.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
=======
django = "^5.0"
django-rest-framework = "^0.1.0"
djangorestframework = "^3.14.0"
django-extensions = "^3.2.3"
django-debug-toolbar = "^4.2.0"
whitenoise = "^6.6.0"
gunicorn = "^21.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
>>>>>>> f6ac5dfbe4ee90a476827f702ef4cb128c0e3ee7
