<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-12-01 20:14
=======
# Generated by Django 5.0 on 2023-12-12 16:37
>>>>>>> f6ac5dfbe4ee90a476827f702ef4cb128c0e3ee7

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
<<<<<<< HEAD
                ("description", models.BooleanField(default=True)),
=======
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("active", models.BooleanField(default=True)),
>>>>>>> f6ac5dfbe4ee90a476827f702ef4cb128c0e3ee7
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
<<<<<<< HEAD
                ("price", models.PositiveIntegerField(null=True)),
=======
                ("price", models.PositiveBigIntegerField(null=True)),
>>>>>>> f6ac5dfbe4ee90a476827f702ef4cb128c0e3ee7
                ("active", models.BooleanField(default=True)),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="product.category"),
                ),
            ],
        ),
    ]
