"""
Django settings for bookstore project.

<<<<<<< HEAD
Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
=======
Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
>>>>>>> f6ac5dfbe4ee90a476827f702ef4cb128c0e3ee7

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
<<<<<<< HEAD
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "*i-xh#mqv_f*pcs2@pzsjuj)e4q$uqha_!2pywlr_z)*27a7f0"
=======
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-x6n^6kv7wn@c@r^6o$af$3(q8bgi=r2!)iwozhx#-oy-9lxudg"
>>>>>>> f6ac5dfbe4ee90a476827f702ef4cb128c0e3ee7

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

<<<<<<< HEAD

ALLOWED_HOSTS = ["localhost",
                 "127.0.0.1",
                 "leonardoitalo.pythonanywhere.com"]
=======
ALLOWED_HOSTS = []
>>>>>>> f6ac5dfbe4ee90a476827f702ef4cb128c0e3ee7


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
<<<<<<< HEAD
    "rest_framework", 
    "django_extensions",
    "debug_toolbar",
    "rest_framework.authtoken",
    "order",
    "product",
=======
    "rest_framework",
    "django_extensions", 
    "order",
    "product",
    "debug_toolbar",
>>>>>>> f6ac5dfbe4ee90a476827f702ef4cb128c0e3ee7
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
<<<<<<< HEAD
=======
    "whitenoise.middleware.WhiteNoiseMiddleware",
>>>>>>> f6ac5dfbe4ee90a476827f702ef4cb128c0e3ee7
]

ROOT_URLCONF = "bookstore.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
<<<<<<< HEAD
        "DIRS": [os.path.join(BASE_DIR, "bookstore", "templates")],
=======
        "DIRS": [],
>>>>>>> f6ac5dfbe4ee90a476827f702ef4cb128c0e3ee7
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "bookstore.wsgi.application"


# Database
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
=======
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
>>>>>>> f6ac5dfbe4ee90a476827f702ef4cb128c0e3ee7

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
<<<<<<< HEAD
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
=======
>>>>>>> f6ac5dfbe4ee90a476827f702ef4cb128c0e3ee7
    }
}


# Password validation
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
=======
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
>>>>>>> f6ac5dfbe4ee90a476827f702ef4cb128c0e3ee7

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.2/topics/i18n/
=======
# https://docs.djangoproject.com/en/5.0/topics/i18n/
>>>>>>> f6ac5dfbe4ee90a476827f702ef4cb128c0e3ee7

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.2/howto/static-files/
=======
# https://docs.djangoproject.com/en/5.0/howto/static-files/
>>>>>>> f6ac5dfbe4ee90a476827f702ef4cb128c0e3ee7

STATIC_URL = "static/"

# Default primary key field type
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


INTERNAL_IPS = ['127.0.0.1',]


REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 5,
        "DEFAULT_AUTHENTICATION_CLASSES": [
            "rest_framework.authentication.BasicAuthentication",
            "rest_framework.authentication.SessionAuthentication",
            "rest_framework.authentication.TokenAuthentication",
    ]
}
#
#    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
#    "PAGE_SIZE": 5
#}
=======
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

INTERNAL_IPS = [
    '127.0.0.1',
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5
}

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATIC_ROOT = BASE_DIR / 'staticfiles'
>>>>>>> f6ac5dfbe4ee90a476827f702ef4cb128c0e3ee7
