# Generated by Django 5.0 on 2023-12-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
        ("product", "0005_remove_product_categories_remove_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ManyToManyField(blank=True, to="product.product"),
        ),
    ]
