# Generated by Django 5.0 on 2023-12-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_order_product"),
        ("product", "0005_remove_product_categories_remove_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ManyToManyField(to="product.product"),
        ),
    ]
